a = input ('digite algo:')
print ('é um numero?',a.isnumeric())
print ('é uma letra?',a.isalpha())
print ('é alfanumerico?',a.isalnum())
print ('esta em maiusculo?',a.isupper())
print ('esta em minusculo?',a.islower())
print ('é a tecla espaço?',a.isspace())
print ('é um numero de 0 a 9?',a.isdecimal())
print ('é imprimivel?',a.isprintable())
print ('é um titulo?',a.istitle())
print ('está dentro da tabela ascii?',a.isascii())
print ('pode ser usado como variavel?',a.isidentifier())
print ('é um numero padrão?',a.isdigit())