n = str (input('Digite seu nome: ')).strip()
maius = n.upper()
minus = n.lower()
se = len(n.replace(' ', ''))
n1 = len (n.split()[0])
print('Nome em maiúsculas:{}'.format(maius))
print('Nome em minúsculas:{}'.format(minus))
print('Total de letras (sem espaços):{}'.format(se))
print('Letras no primeiro nome:{}'.format(n1))